CRITICAL - 2022-11-25 22:26:09 --> The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 224.
 1 SYSTEMPATH\CodeIgniter.php(224): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(182): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 FCPATH\index.php(55): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2022-11-25 22:28:25 --> The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 224.
 1 SYSTEMPATH\CodeIgniter.php(224): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(182): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 FCPATH\index.php(55): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2022-11-25 22:28:28 --> The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 224.
 1 SYSTEMPATH\CodeIgniter.php(224): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(182): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 FCPATH\index.php(55): CodeIgniter\CodeIgniter->initialize()
ERROR - 2022-11-25 15:29:11 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\xampp\htdocs\CodeIgniter4\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'apiproductos', 3306, '', 0)
#1 C:\xampp\htdocs\CodeIgniter4\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\CodeIgniter4\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\CodeIgniter4\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\CodeIgniter4\system\Model.php(240): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\CodeIgniter4\system\BaseModel.php(586): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\CodeIgniter4\app\Controllers\Products.php(14): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\CodeIgniter4\system\CodeIgniter.php(927): App\Controllers\Products->index()
#8 C:\xampp\htdocs\CodeIgniter4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Products))
#9 C:\xampp\htdocs\CodeIgniter4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\CodeIgniter4\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\xampp\htdocs\CodeIgniter4\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\CodeIgniter4\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\CodeIgniter4\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\CodeIgniter4\system\Model.php(240): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\CodeIgniter4\system\BaseModel.php(586): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\CodeIgniter4\app\Controllers\Products.php(14): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\CodeIgniter4\system\CodeIgniter.php(927): App\Controllers\Products->index()
#7 C:\xampp\htdocs\CodeIgniter4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Products))
#8 C:\xampp\htdocs\CodeIgniter4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\CodeIgniter4\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-11-25 15:29:11 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `product`', [], false)
 3 SYSTEMPATH\Model.php(240): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(586): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Products.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Products->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Products))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-11-25 15:32:21 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\xampp\htdocs\CodeIgniter4\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'pelis', 3306, '', 0)
#1 C:\xampp\htdocs\CodeIgniter4\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\CodeIgniter4\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\CodeIgniter4\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\CodeIgniter4\system\Model.php(240): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\CodeIgniter4\system\BaseModel.php(586): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\CodeIgniter4\app\Controllers\Products.php(14): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\CodeIgniter4\system\CodeIgniter.php(927): App\Controllers\Products->index()
#8 C:\xampp\htdocs\CodeIgniter4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Products))
#9 C:\xampp\htdocs\CodeIgniter4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\CodeIgniter4\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\xampp\htdocs\CodeIgniter4\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\CodeIgniter4\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\CodeIgniter4\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\CodeIgniter4\system\Model.php(240): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\CodeIgniter4\system\BaseModel.php(586): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\CodeIgniter4\app\Controllers\Products.php(14): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\CodeIgniter4\system\CodeIgniter.php(927): App\Controllers\Products->index()
#7 C:\xampp\htdocs\CodeIgniter4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Products))
#8 C:\xampp\htdocs\CodeIgniter4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\CodeIgniter4\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-11-25 15:32:21 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `product`', [], false)
 3 SYSTEMPATH\Model.php(240): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(586): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Products.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Products->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Products))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-11-25 15:33:22 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\CodeIgniter4\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '123456789', 'pelis', 3307, '', 0)
#1 C:\xampp\htdocs\CodeIgniter4\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\CodeIgniter4\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\CodeIgniter4\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\CodeIgniter4\system\Model.php(240): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\CodeIgniter4\system\BaseModel.php(586): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\CodeIgniter4\app\Controllers\Products.php(14): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\CodeIgniter4\system\CodeIgniter.php(927): App\Controllers\Products->index()
#8 C:\xampp\htdocs\CodeIgniter4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Products))
#9 C:\xampp\htdocs\CodeIgniter4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\CodeIgniter4\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\CodeIgniter4\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\CodeIgniter4\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\CodeIgniter4\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\CodeIgniter4\system\Model.php(240): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\CodeIgniter4\system\BaseModel.php(586): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\CodeIgniter4\app\Controllers\Products.php(14): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\CodeIgniter4\system\CodeIgniter.php(927): App\Controllers\Products->index()
#7 C:\xampp\htdocs\CodeIgniter4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Products))
#8 C:\xampp\htdocs\CodeIgniter4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\CodeIgniter4\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-11-25 15:33:22 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `product`', [], false)
 3 SYSTEMPATH\Model.php(240): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(586): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Products.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Products->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Products))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-11-25 15:34:36 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\CodeIgniter4\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '123456789', 'pelis', 3307, '', 0)
#1 C:\xampp\htdocs\CodeIgniter4\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\CodeIgniter4\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\CodeIgniter4\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\CodeIgniter4\system\Model.php(240): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\CodeIgniter4\system\BaseModel.php(586): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\CodeIgniter4\app\Controllers\Products.php(14): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\CodeIgniter4\system\CodeIgniter.php(927): App\Controllers\Products->index()
#8 C:\xampp\htdocs\CodeIgniter4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Products))
#9 C:\xampp\htdocs\CodeIgniter4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\CodeIgniter4\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\CodeIgniter4\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\CodeIgniter4\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\CodeIgniter4\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\CodeIgniter4\system\Model.php(240): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\CodeIgniter4\system\BaseModel.php(586): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\CodeIgniter4\app\Controllers\Products.php(14): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\CodeIgniter4\system\CodeIgniter.php(927): App\Controllers\Products->index()
#7 C:\xampp\htdocs\CodeIgniter4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Products))
#8 C:\xampp\htdocs\CodeIgniter4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\CodeIgniter4\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-11-25 15:34:36 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `product`', [], false)
 3 SYSTEMPATH\Model.php(240): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(586): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Products.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Products->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Products))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-11-25 15:34:38 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\CodeIgniter4\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '123456789', 'pelis', 3307, '', 0)
#1 C:\xampp\htdocs\CodeIgniter4\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\CodeIgniter4\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\CodeIgniter4\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\CodeIgniter4\system\Model.php(240): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\CodeIgniter4\system\BaseModel.php(586): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\CodeIgniter4\app\Controllers\Products.php(14): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\CodeIgniter4\system\CodeIgniter.php(927): App\Controllers\Products->index()
#8 C:\xampp\htdocs\CodeIgniter4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Products))
#9 C:\xampp\htdocs\CodeIgniter4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\CodeIgniter4\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\CodeIgniter4\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\CodeIgniter4\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\CodeIgniter4\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\CodeIgniter4\system\Model.php(240): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\CodeIgniter4\system\BaseModel.php(586): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\CodeIgniter4\app\Controllers\Products.php(14): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\CodeIgniter4\system\CodeIgniter.php(927): App\Controllers\Products->index()
#7 C:\xampp\htdocs\CodeIgniter4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Products))
#8 C:\xampp\htdocs\CodeIgniter4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\CodeIgniter4\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-11-25 15:34:38 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `product`', [], false)
 3 SYSTEMPATH\Model.php(240): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(586): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Products.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Products->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Products))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-11-25 15:36:20 --> mysqli_sql_exception: Table 'pelis.product' doesn't exist in C:\xampp\htdocs\CodeIgniter4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\CodeIgniter4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\CodeIgniter4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\CodeIgniter4\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\CodeIgniter4\system\Model.php(240): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\CodeIgniter4\system\BaseModel.php(586): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\CodeIgniter4\app\Controllers\Products.php(14): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\CodeIgniter4\system\CodeIgniter.php(927): App\Controllers\Products->index()
#8 C:\xampp\htdocs\CodeIgniter4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Products))
#9 C:\xampp\htdocs\CodeIgniter4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\CodeIgniter4\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2022-11-25 15:36:20 --> Table 'pelis.product' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *
FROM `product`', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `product`')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `product`')
 4 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `product`', [], false)
 5 SYSTEMPATH\Model.php(240): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\BaseModel.php(586): CodeIgniter\Model->doFindAll(0, 0)
 7 APPPATH\Controllers\Products.php(14): CodeIgniter\BaseModel->findAll()
 8 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Products->index()
 9 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Products))
10 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-11-25 15:38:10 --> mysqli_sql_exception: Table 'pelis.product' doesn't exist in C:\xampp\htdocs\CodeIgniter4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\CodeIgniter4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\CodeIgniter4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\CodeIgniter4\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\CodeIgniter4\system\Model.php(240): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\CodeIgniter4\system\BaseModel.php(586): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\CodeIgniter4\app\Controllers\Pelis.php(14): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\CodeIgniter4\system\CodeIgniter.php(927): App\Controllers\pelis->index()
#8 C:\xampp\htdocs\CodeIgniter4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pelis))
#9 C:\xampp\htdocs\CodeIgniter4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\CodeIgniter4\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2022-11-25 15:38:10 --> Table 'pelis.product' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *
FROM `product`', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `product`')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `product`')
 4 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `product`', [], false)
 5 SYSTEMPATH\Model.php(240): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\BaseModel.php(586): CodeIgniter\Model->doFindAll(0, 0)
 7 APPPATH\Controllers\Pelis.php(14): CodeIgniter\BaseModel->findAll()
 8 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\pelis->index()
 9 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pelis))
10 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
